// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: preferences.proto
// Protobuf Java Version: 4.31.1

package edu.osu.tictactoecompose.common;

/**
 * Protobuf type {@code Preferences}
 */
@com.google.protobuf.Generated
public final class Preferences extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Preferences)
    PreferencesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      Preferences.class.getName());
  }
  // Use Preferences.newBuilder() to construct.
  private Preferences(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Preferences() {
    mediaId_ = "";
    artworkOriginalUri_ = "";
    artworkData_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PreferencesOuterClass.internal_static_Preferences_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PreferencesOuterClass.internal_static_Preferences_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Preferences.class, Preferences.Builder.class);
  }

  public static final int MEDIA_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object mediaId_ = "";
  /**
   * <pre>
   * The media id of the last played item.
   * </pre>
   *
   * <code>string media_id = 1;</code>
   * @return The mediaId.
   */
  @Override
  public String getMediaId() {
    Object ref = mediaId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      mediaId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The media id of the last played item.
   * </pre>
   *
   * <code>string media_id = 1;</code>
   * @return The bytes for mediaId.
   */
  @Override
  public com.google.protobuf.ByteString
      getMediaIdBytes() {
    Object ref = mediaId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      mediaId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_MS_FIELD_NUMBER = 2;
  private long positionMs_ = 0L;
  /**
   * <pre>
   * The position in the last played item in milliseconds.
   * </pre>
   *
   * <code>int64 position_ms = 2;</code>
   * @return The positionMs.
   */
  @Override
  public long getPositionMs() {
    return positionMs_;
  }

  public static final int ARTWORK_ORIGINAL_URI_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object artworkOriginalUri_ = "";
  /**
   * <pre>
   * The original artwork URI of the last played item.
   * </pre>
   *
   * <code>string artwork_original_uri = 3;</code>
   * @return The artworkOriginalUri.
   */
  @Override
  public String getArtworkOriginalUri() {
    Object ref = artworkOriginalUri_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      artworkOriginalUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The original artwork URI of the last played item.
   * </pre>
   *
   * <code>string artwork_original_uri = 3;</code>
   * @return The bytes for artworkOriginalUri.
   */
  @Override
  public com.google.protobuf.ByteString
      getArtworkOriginalUriBytes() {
    Object ref = artworkOriginalUri_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      artworkOriginalUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARTWORK_DATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString artworkData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The artwork image data of the last played item.
   * </pre>
   *
   * <code>bytes artwork_data = 4;</code>
   * @return The artworkData.
   */
  @Override
  public com.google.protobuf.ByteString getArtworkData() {
    return artworkData_;
  }

  public static final int DURATION_MS_FIELD_NUMBER = 5;
  private long durationMs_ = 0L;
  /**
   * <pre>
   * The duration of the last played item in milliseconds, or C.TIME_UNSET if
   * unknown.
   * </pre>
   *
   * <code>int64 duration_ms = 5;</code>
   * @return The durationMs.
   */
  @Override
  public long getDurationMs() {
    return durationMs_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mediaId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, mediaId_);
    }
    if (positionMs_ != 0L) {
      output.writeInt64(2, positionMs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(artworkOriginalUri_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, artworkOriginalUri_);
    }
    if (!artworkData_.isEmpty()) {
      output.writeBytes(4, artworkData_);
    }
    if (durationMs_ != 0L) {
      output.writeInt64(5, durationMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mediaId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, mediaId_);
    }
    if (positionMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, positionMs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(artworkOriginalUri_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, artworkOriginalUri_);
    }
    if (!artworkData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, artworkData_);
    }
    if (durationMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, durationMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Preferences)) {
      return super.equals(obj);
    }
    Preferences other = (Preferences) obj;

    if (!getMediaId()
        .equals(other.getMediaId())) return false;
    if (getPositionMs()
        != other.getPositionMs()) return false;
    if (!getArtworkOriginalUri()
        .equals(other.getArtworkOriginalUri())) return false;
    if (!getArtworkData()
        .equals(other.getArtworkData())) return false;
    if (getDurationMs()
        != other.getDurationMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MEDIA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMediaId().hashCode();
    hash = (37 * hash) + POSITION_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPositionMs());
    hash = (37 * hash) + ARTWORK_ORIGINAL_URI_FIELD_NUMBER;
    hash = (53 * hash) + getArtworkOriginalUri().hashCode();
    hash = (37 * hash) + ARTWORK_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getArtworkData().hashCode();
    hash = (37 * hash) + DURATION_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDurationMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Preferences parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Preferences parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Preferences parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Preferences parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Preferences parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Preferences parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Preferences parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static Preferences parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Preferences parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Preferences parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Preferences parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static Preferences parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Preferences prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
      return new Builder(parent);
  }
  /**
   * Protobuf type {@code Preferences}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Preferences)
      PreferencesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PreferencesOuterClass.internal_static_Preferences_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PreferencesOuterClass.internal_static_Preferences_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Preferences.class, Preferences.Builder.class);
    }

    // Construct using Preferences.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mediaId_ = "";
      positionMs_ = 0L;
      artworkOriginalUri_ = "";
      artworkData_ = com.google.protobuf.ByteString.EMPTY;
      durationMs_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PreferencesOuterClass.internal_static_Preferences_descriptor;
    }

    @Override
    public Preferences getDefaultInstanceForType() {
      return Preferences.getDefaultInstance();
    }

    @Override
    public Preferences build() {
      Preferences result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Preferences buildPartial() {
      Preferences result = new Preferences(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Preferences result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.mediaId_ = mediaId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.positionMs_ = positionMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.artworkOriginalUri_ = artworkOriginalUri_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.artworkData_ = artworkData_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.durationMs_ = durationMs_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Preferences) {
        return mergeFrom((Preferences)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Preferences other) {
      if (other == Preferences.getDefaultInstance()) return this;
      if (!other.getMediaId().isEmpty()) {
        mediaId_ = other.mediaId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getPositionMs() != 0L) {
        setPositionMs(other.getPositionMs());
      }
      if (!other.getArtworkOriginalUri().isEmpty()) {
        artworkOriginalUri_ = other.artworkOriginalUri_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getArtworkData().isEmpty()) {
        setArtworkData(other.getArtworkData());
      }
      if (other.getDurationMs() != 0L) {
        setDurationMs(other.getDurationMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              mediaId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              positionMs_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              artworkOriginalUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              artworkData_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              durationMs_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object mediaId_ = "";
    /**
     * <pre>
     * The media id of the last played item.
     * </pre>
     *
     * <code>string media_id = 1;</code>
     * @return The mediaId.
     */
    public String getMediaId() {
      Object ref = mediaId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mediaId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The media id of the last played item.
     * </pre>
     *
     * <code>string media_id = 1;</code>
     * @return The bytes for mediaId.
     */
    public com.google.protobuf.ByteString
        getMediaIdBytes() {
      Object ref = mediaId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mediaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The media id of the last played item.
     * </pre>
     *
     * <code>string media_id = 1;</code>
     * @param value The mediaId to set.
     * @return This builder for chaining.
     */
    public Builder setMediaId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      mediaId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The media id of the last played item.
     * </pre>
     *
     * <code>string media_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaId() {
      mediaId_ = getDefaultInstance().getMediaId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The media id of the last played item.
     * </pre>
     *
     * <code>string media_id = 1;</code>
     * @param value The bytes for mediaId to set.
     * @return This builder for chaining.
     */
    public Builder setMediaIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mediaId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long positionMs_ ;
    /**
     * <pre>
     * The position in the last played item in milliseconds.
     * </pre>
     *
     * <code>int64 position_ms = 2;</code>
     * @return The positionMs.
     */
    @Override
    public long getPositionMs() {
      return positionMs_;
    }
    /**
     * <pre>
     * The position in the last played item in milliseconds.
     * </pre>
     *
     * <code>int64 position_ms = 2;</code>
     * @param value The positionMs to set.
     * @return This builder for chaining.
     */
    public Builder setPositionMs(long value) {

      positionMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The position in the last played item in milliseconds.
     * </pre>
     *
     * <code>int64 position_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPositionMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      positionMs_ = 0L;
      onChanged();
      return this;
    }

    private Object artworkOriginalUri_ = "";
    /**
     * <pre>
     * The original artwork URI of the last played item.
     * </pre>
     *
     * <code>string artwork_original_uri = 3;</code>
     * @return The artworkOriginalUri.
     */
    public String getArtworkOriginalUri() {
      Object ref = artworkOriginalUri_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        artworkOriginalUri_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The original artwork URI of the last played item.
     * </pre>
     *
     * <code>string artwork_original_uri = 3;</code>
     * @return The bytes for artworkOriginalUri.
     */
    public com.google.protobuf.ByteString
        getArtworkOriginalUriBytes() {
      Object ref = artworkOriginalUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        artworkOriginalUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The original artwork URI of the last played item.
     * </pre>
     *
     * <code>string artwork_original_uri = 3;</code>
     * @param value The artworkOriginalUri to set.
     * @return This builder for chaining.
     */
    public Builder setArtworkOriginalUri(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      artworkOriginalUri_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The original artwork URI of the last played item.
     * </pre>
     *
     * <code>string artwork_original_uri = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearArtworkOriginalUri() {
      artworkOriginalUri_ = getDefaultInstance().getArtworkOriginalUri();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The original artwork URI of the last played item.
     * </pre>
     *
     * <code>string artwork_original_uri = 3;</code>
     * @param value The bytes for artworkOriginalUri to set.
     * @return This builder for chaining.
     */
    public Builder setArtworkOriginalUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      artworkOriginalUri_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString artworkData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The artwork image data of the last played item.
     * </pre>
     *
     * <code>bytes artwork_data = 4;</code>
     * @return The artworkData.
     */
    @Override
    public com.google.protobuf.ByteString getArtworkData() {
      return artworkData_;
    }
    /**
     * <pre>
     * The artwork image data of the last played item.
     * </pre>
     *
     * <code>bytes artwork_data = 4;</code>
     * @param value The artworkData to set.
     * @return This builder for chaining.
     */
    public Builder setArtworkData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      artworkData_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The artwork image data of the last played item.
     * </pre>
     *
     * <code>bytes artwork_data = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearArtworkData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      artworkData_ = getDefaultInstance().getArtworkData();
      onChanged();
      return this;
    }

    private long durationMs_ ;
    /**
     * <pre>
     * The duration of the last played item in milliseconds, or C.TIME_UNSET if
     * unknown.
     * </pre>
     *
     * <code>int64 duration_ms = 5;</code>
     * @return The durationMs.
     */
    @Override
    public long getDurationMs() {
      return durationMs_;
    }
    /**
     * <pre>
     * The duration of the last played item in milliseconds, or C.TIME_UNSET if
     * unknown.
     * </pre>
     *
     * <code>int64 duration_ms = 5;</code>
     * @param value The durationMs to set.
     * @return This builder for chaining.
     */
    public Builder setDurationMs(long value) {

      durationMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The duration of the last played item in milliseconds, or C.TIME_UNSET if
     * unknown.
     * </pre>
     *
     * <code>int64 duration_ms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      durationMs_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Preferences)
  }

  // @@protoc_insertion_point(class_scope:Preferences)
  private static final Preferences DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Preferences();
  }

  public static Preferences getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Preferences>
      PARSER = new com.google.protobuf.AbstractParser<Preferences>() {
    @Override
    public Preferences parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Preferences> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Preferences> getParserForType() {
    return PARSER;
  }

  @Override
  public Preferences getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

