// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: preferences.proto
// Protobuf Java Version: 4.31.1

package edu.osu.tictactoecompose.common;

@com.google.protobuf.Generated
public final class PreferencesOuterClass {
  private PreferencesOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      PreferencesOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Preferences_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_Preferences_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021preferences.proto\022\034androidx.media3.dem" +
      "o.session\"}\n\013Preferences\022\020\n\010media_id\030\001 \001" +
      "(\t\022\023\n\013position_ms\030\002 \001(\003\022\034\n\024artwork_origi" +
      "nal_uri\030\003 \001(\t\022\024\n\014artwork_data\030\004 \001(\014\022\023\n\013d" +
      "uration_ms\030\005 \001(\003B \n\034androidx.media3.demo" +
      ".sessionP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Preferences_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Preferences_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_Preferences_descriptor,
        new String[] { "MediaId", "PositionMs", "ArtworkOriginalUri", "ArtworkData", "DurationMs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
