// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: preferences.proto
// Protobuf Java Version: 4.31.1

package edu.osu.tictactoecompose.common;

@com.google.protobuf.Generated
public interface PreferencesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:androidx.media3.demo.session.Preferences)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The media id of the last played item.
   * </pre>
   *
   * <code>string media_id = 1;</code>
   * @return The mediaId.
   */
  String getMediaId();
  /**
   * <pre>
   * The media id of the last played item.
   * </pre>
   *
   * <code>string media_id = 1;</code>
   * @return The bytes for mediaId.
   */
  com.google.protobuf.ByteString
      getMediaIdBytes();

  /**
   * <pre>
   * The position in the last played item in milliseconds.
   * </pre>
   *
   * <code>int64 position_ms = 2;</code>
   * @return The positionMs.
   */
  long getPositionMs();

  /**
   * <pre>
   * The original artwork URI of the last played item.
   * </pre>
   *
   * <code>string artwork_original_uri = 3;</code>
   * @return The artworkOriginalUri.
   */
  String getArtworkOriginalUri();
  /**
   * <pre>
   * The original artwork URI of the last played item.
   * </pre>
   *
   * <code>string artwork_original_uri = 3;</code>
   * @return The bytes for artworkOriginalUri.
   */
  com.google.protobuf.ByteString
      getArtworkOriginalUriBytes();

  /**
   * <pre>
   * The artwork image data of the last played item.
   * </pre>
   *
   * <code>bytes artwork_data = 4;</code>
   * @return The artworkData.
   */
  com.google.protobuf.ByteString getArtworkData();

  /**
   * <pre>
   * The duration of the last played item in milliseconds, or C.TIME_UNSET if
   * unknown.
   * </pre>
   *
   * <code>int64 duration_ms = 5;</code>
   * @return The durationMs.
   */
  long getDurationMs();
}
